### PR TITLE
ISL: Fix gcc 8, only builds with isl-0.18

### PR DESCRIPTION
**Pull request by franzflasch**
GCC 8 only builds with isl-0.18. With isl-0.20 I get a bunch of isl related errors. Suggested fix on the GCC mailing lists is to use version 0.18

### CODE REVIEW

**Comment by USBhost** [comment]
This must be recent because I built 8 like a week ago and was fine. Did you try isl 0.19?

**Comment by franzflasch** [comment]
No, I didn't try it, maybe works with 0.19.

Just saw in the mail archives, that the default version for GCC8 is 0.18:

https://www.mail-archive.com/gcc-bugs@gcc.gnu.org/msg582009.html

**Comment by USBhost** [comment]
GCC 8 builds for me (as of time of writing) @franzflasch .
Can you give me the build error?

**Comment by franzflasch** [comment]
it is exaclty the same error as you can see in the mail archives: 
https://www.mail-archive.com/gcc-bugs@gcc.gnu.org/msg582007.html

**Comment by USBhost** [comment]
Please wipe all your sources and redownload them. 
Or simply reclone then try again.

And give me your command line ("./build etc..."). So I can try reproducing your problem.

**Comment by franzflasch** [comment]
OK, will close the issue, I am already refactoring the whole code on my fork.

**Comment by krasCGQ** [comment]
@franzflasch
Assuming you're building from release tarball: Maybe try to build from latest git source?

Because it builds just fine on my system, even with my heavily modified fork that tracks master/snapshot branch of each repositories.

**Comment by franzflasch** [comment]
For which target architecture did you build? For arm I always get an error.

**Comment by USBhost** [comment]
Can you give me your command line ("./build etc...") @franzflasch

**Comment by franzflasch** [comment]
Currently not, I am currently working on my own fork, however I will try to reproduce it.

**Comment by franzflasch** [comment]
I think for tools like this one it is essential to have a CI system which is rebuilding every possible combination, as soon as there are changes in the code. I tried to setup a build-matrix using travis ci, however I always run into the timeout of 50 minutes. Do you know any alternative CI like travis CI without any timeout?

**Comment by krasCGQ** [comment]
@franzflasch ARM, AArch64 (ARM64), and x86_64 are all built just fine for me.

**Pull request closed without merging**
