### PR TITLE
add autoconf-archive for arch

### PR DESCRIPTION
**Pull request by flipflop133**
autoconf-archive is required to build axel on arch

### CODE REVIEW

**Comment by USBhost** [comment]
Arch now has autoconf-archive in the official repos?

**Comment by flipflop133** [comment]
In community only.

**Comment by flipflop133** [comment]
So we should build it in the script?

**Comment by USBhost** [comment]
> So we should build it in the script?

This is the problem the only way to build it is to use community packages. If we are going to use community packages might as well just install what we want, no need to build it. #32

**Pull request closed without merging**
